# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: madelwau <madelwau@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/04 12:58:29 by madelwau          #+#    #+#              #
#    Updated: 2026/09/03 16:58:18 by madelwau         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SHELL	:=	/bin/sh

NAME	:= $(strip philo)

CC		:= cc
CFLAGS	:= -Wall -Wextra -Werror -I. -MMD -MP

LIBS	:= -lreadline

SRCS	:= main.c routines.c utils.c parsing.c
MODE	:= mandatory

OBJ_DIR	:= .obj/
OBJS	:= $(addprefix $(OBJ_DIR), $(SRCS:.c=.o))
DEPS	:= $(addprefix $(OBJ_DIR), $(SRCS:.c=.d))

all: $(NAME)

$(NAME): $(OBJS)
	@$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o $(NAME)
	@printf '$(COL_Y)[DONE] %s ($(MODE))$(COL_0)\n' "$(NAME)"

$(OBJ_DIR)%.o: %.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -I$(LFT_DIR) -I. -c $< -o $@
	@printf "$(COL_G)[OK]$(COL_0) %s -> %s\n" "$<" "$@"

clean:
	@rm -rf $(OBJ_DIR)
	@printf "$(COL_R)[RM]$(COL_0) %s/%s\n" "$(shell basename $(CURDIR))" "$(OBJ_DIR)"

fclean: clean
	@rm -f $(NAME)
	@printf "$(COL_R)[RM]$(COL_0) $(COL_B)%s$(COL_0)\n" "$(NAME)"

re: fclean all

.PHONY: all clean fclean re
-include $(DEPS)

# Colors
COL_R	:= \033[1;31m
COL_G	:= \033[1;32m
COL_B	:= \033[1;34m
COL_Y	:= \033[1;33m
COL_0	:= \033[0m
